### ISSUE TITLE
Solve Problem1 : p1_insertAtPosition.cpp

### ISSUE THREAD

**Issue by Akash88585** [Akash88585/ProgrammingProblemSolving#2]
Insert the number "num" at the desired position in vector "numlist".
Number "num" can be inserted at the position where it is greater than previous and less than next element.
If number "num" is lowest then insert at 1st position else if highest, then insert at last position.
In any other case return "numlist".
File location : c++/p1_insertAtPosition.cpp

**Comment by Alok5102R** [comment]
Can you assign this to me?

**Comment by Akash88585** [comment]
Yes @Alok5102R you can start.

**Comment by Alok5102R** [comment]
Have a look at my [PR](https://github.com/Akash88585/ProgrammingProblemSolving/pull/10/commits/1f5edcd060c3e40470a12a1c934d71f311246cf0)

@Akash88585

**Comment by Akash88585** [comment]
Good @Alok5102R
