### ISSUE TITLE
Text visibility issue and UI fix

### ISSUE THREAD

**Issue by Alok5102R** [Akash88585/ProgrammingProblemSolving#26]
Question description text isn't visible properly and other UI fixes are required.
Assign this issue to me, so that I can fix it.

**Comment by Akash88585** [comment]
Yes you can start @Alok5102R

**Comment by SagarKumar2840** [comment]
Can I proceed with this issue @Akash88585 ?

**Comment by Akash88585** [comment]
Sure you can proceed @SagarKumar2840

**Comment by Akash88585** [comment]
Thanks @SagarKumar2840
