### ISSUE TITLE
Solve Problem1 : p1_insertAtPosition.py

### ISSUE THREAD

**Issue by Akash88585** [Akash88585/ProgrammingProblemSolving#3]
Insert the number "num" at the desired position in list "numlist".
Number "num" can be inserted at the position where it is greater than previous and less than next element.
If number "num" is lowest then insert at 1st position else if highest, then insert at last position.
In any other case return "numlist".
File location : python/p1_insertAtPosition.py

**Comment by surreal30** [comment]
Hi assign this to me please.
